Run formatter

diff --git a/git-standup b/git-standup
--- a/git-standup
+++ b/git-standup
@@ -2,7 +2,7 @@
 
 # Shows the usage
 function usage() {
-  cat <<EOS
+  cat << EOS
 Usage:
   git standup [-a <author name>] [-w <weekstart-weekend>] [-d <since-days-ago>] [-u <until-days-ago>] [-m <max-dir-depth>] [-g] [-h] [-f] [-c]
 
@@ -41,7 +41,6 @@ function colored() {
   NORMAL=$(tput sgr0)
 
   GIT_PRETTY_DATE="%cd"
-  # shellcheck disable=SC2154
   if [[ $option_R ]]; then
     GIT_PRETTY_DATE="%ad"
   fi
@@ -49,7 +48,6 @@ function colored() {
   GIT_PRETTY_FORMAT="%Cred%h%Creset - %s %Cgreen($GIT_PRETTY_DATE) %C(bold blue)<%an>%Creset"
   COLOR=always
 
-  # shellcheck disable=SC2154
   if [[ $option_g ]]; then
     GIT_PRETTY_FORMAT="$GIT_PRETTY_FORMAT %C(yellow)gpg: %G?%Creset"
   fi
@@ -57,11 +55,9 @@ function colored() {
 
 # Sets up the uncolored output
 function uncolored() {
-  # shellcheck disable=SC2034
   RED=""
   GREEN=""
   YELLOW=""
-  # shellcheck disable=SC2034
   BLUE=""
   BOLD=""
   UNDERLINE=""
@@ -83,41 +79,39 @@ function uncolored() {
 }
 
 function writeFile() {
-  echo -e "$1" >>"${REPORT_FILE_PATH}"
+  echo -e $1 >> "${REPORT_FILE_PATH}"
 }
 
 function runStandup() {
   # Fetch the latest commits, if required
-  # shellcheck disable=SC2154
   if [[ $option_f ]]; then
     echo "${BOLD}${GREEN}Fetching commits in ${YELLOW}${UNDERLINE}${BOLD}${BASENAME}${NORMAL}"
-    git fetch --all >/dev/null 2>&1
+    git fetch --all > /dev/null 2>&1
   fi
 
   {
-    GITOUT=$(eval "${GIT_LOG_COMMAND}" 2>/dev/null)
+    GITOUT=$(eval ${GIT_LOG_COMMAND} 2> /dev/null)
   } || {
     GITOUT=""
   }
 
   # If `r` option was given then no output, just write the report
-  # shellcheck disable=SC2154
-  if [[ -n $option_r ]]; then
+  if [[ ! -z $option_r ]]; then
     echo "Generating report for: ${CUR_DIR}"
 
-    if [[ -n $GITOUT ]]; then
+    if [[ ! -z "$GITOUT" ]]; then
       writeFile "${CUR_DIR}\n $GITOUT"
     elif [[ -z $option_s ]]; then
       writeFile "${CUR_DIR}\n No activity found!\n"
     fi
   else
     ## Only output if there is some activity
-    if [[ -n $GITOUT ]]; then
+    if [[ ! -z "$GITOUT" ]]; then
       echo "${BOLD}${UNDERLINE}${YELLOW}$CUR_DIR${NORMAL}"
       echo "$GITOUT"
     elif [[ -z $option_s ]]; then ## Show the no activity message only if the `s` flag is not there
       echo "${BOLD}${UNDERLINE}${YELLOW}$CUR_DIR${NORMAL}"
-      if [[ ${AUTHOR} == '.*' ]]; then
+      if [[ ${AUTHOR} = '.*' ]]; then
         echo "${YELLOW}No commits found during this period.${NORMAL}"
       else
         echo "${YELLOW}No commits from $AUTHOR during this period.${NORMAL}"
@@ -141,22 +135,21 @@ done
 shift $((OPTIND - 1))
 
 if [[ $# -gt 0 ]]; then
-  echo >&2 "Invalid arguments: $*"
+  echo >&2 "Invalid arguments: $@"
   echo >&2 "Use 'git standup -h' to see usage info"
   exit 1
 fi
 
 # Main script
-# shellcheck disable=SC2154
 if [[ $option_h ]]; then
   usage
   exit 0
 fi
 
 # Use colors, but only if connected to a terminal, and that terminal supports them.
-if [[ -t 1 ]] && [[ -n $TERM ]] && which tput &>/dev/null && tput colors &>/dev/null; then
+if [[ -t 1 ]] && [[ -n "$TERM" ]] && which tput &> /dev/null && tput colors &> /dev/null; then
   ncolors=$(tput colors)
-  if [[ -n $ncolors ]] && [[ $ncolors -ge 8 ]] && [[ -z $option_r ]]; then
+  if [[ -n "$ncolors" ]] && [[ "$ncolors" -ge 8 ]] && [[ -z "$option_r" ]]; then
     colored
   else
     uncolored
@@ -174,35 +167,31 @@ REPORT_FILE_PATH="${RAN_FROM_DIR}/git-standup-report.txt"
 STAT=
 
 # If report is to be generated, remove the existing report file if any
-if [[ -n $option_r ]]; then
-  rm -rf "${REPORT_FILE_PATH}"
+if [[ ! -z $option_r ]]; then
+  rm -rf ${REPORT_FILE_PATH}
 fi
 
-# shellcheck disable=SC2154
 if [[ $option_m ]]; then
-  MAXDEPTH="$((option_m + 1))"
+  MAXDEPTH="$(($option_m + 1))"
 fi
 
-# shellcheck disable=SC2154
 if [[ $option_L ]]; then
   INCLUDE_LINKS="-L"
 fi
 
-# shellcheck disable=SC2154
 if [[ $option_c ]]; then
   STAT="--stat"
 fi
 
 ## If -d flag is there, use its value for the since
-# shellcheck disable=SC2154
 if [[ $option_d ]] && [[ $option_d -ne 0 ]]; then
   SINCE="$option_d days ago"
 else
   ## -d flag is not there, go on with the normal processing
-  WEEKSTART="$(cut -d '-' -f 1 <<<"$option_w")"
+  WEEKSTART="$(cut -d '-' -f 1 <<< "$option_w")"
   WEEKSTART=${WEEKSTART:="Mon"}
 
-  WEEKEND="$(cut -d '-' -f 2 <<<"$option_w")"
+  WEEKEND="$(cut -d '-' -f 2 <<< "$option_w")"
   WEEKEND=${WEEKEND:="Fri"}
 
   ## In case it is the start of week, we need to
@@ -214,14 +203,12 @@ else
 fi
 
 ## If -u flag is there, use its value for the until
-# shellcheck disable=SC2154
 if [[ $option_u ]] && [[ $option_u -ne 0 ]]; then
   UNTIL_OPT="--until=\"$option_u days ago\""
 elif [[ $option_B ]]; then
   UNTIL_OPT="--until=\"$option_B\""
 fi
 
-# shellcheck disable=SC2154
 if [[ $option_A ]]; then
   AFTER_OPT="--after=\"$option_A\""
 fi
@@ -229,7 +216,6 @@ fi
 GIT_DATE_FORMAT=${option_D:-relative}
 
 # For when the command has been run in a non-repo directory
-# shellcheck disable=SC2154
 if [[ $option_F || ! -d ".git" || -f ".git" ]]; then
   BASE_DIR=$(pwd)
   # Set delimiter to newline for the loop
@@ -249,10 +235,9 @@ fi
 
 # if project directories is still empty
 # we might be sitting inside a git repo
-# shellcheck disable=SC2128
 if [[ -z ${PROJECT_DIRS} ]]; then
   ROOT_DIR_COMMAND="git rev-parse --show-toplevel"
-  PROJECT_ROOT=$(eval "${ROOT_DIR_COMMAND}" 2>/dev/null)
+  PROJECT_ROOT=$(eval ${ROOT_DIR_COMMAND} 2> /dev/null)
 
   if [[ -z ${PROJECT_ROOT} ]]; then
     echo "${YELLOW}You must be inside a git repository!${NORMAL}"
@@ -264,26 +249,23 @@ fi
 
 # Foreach of the project directories, run the standup
 IFS=$'\n'
-for DIR in "${PROJECT_DIRS[@]}"; do
+for DIR in ${PROJECT_DIRS}; do
   PROJECT_DIR=$(dirname "$DIR")
-  # shellcheck disable=2164
   cd "$PROJECT_DIR"
   CUR_DIR=$(pwd)
   BASENAME=$(basename "$CUR_DIR")
 
   # continue if not a git directory
   if [[ ! -d ".git" || -f ".git" ]]; then
-    # shellcheck disable=2164
-    cd "${BASE_DIR}"
+    cd ${BASE_DIR}
     continue
   fi
 
   AUTHOR=$(git config user.name)
 
-  # shellcheck disable=2154
   if [[ $option_a ]]; then
     # In case the parameter
-    if [[ $option_a == 'all' ]]; then
+    if [[ $option_a = 'all' ]]; then
       AUTHOR=".*"
     else
       AUTHOR="$option_a"
@@ -291,7 +273,6 @@ for DIR in "${PROJECT_DIRS[@]}"; do
   fi
 
   GIT_BRANCH_FILTER="--all"
-  # shellcheck disable=2154
   if [[ $option_b ]]; then
     GIT_BRANCH_FILTER="--first-parent $option_b"
   fi
@@ -312,7 +293,6 @@ for DIR in "${PROJECT_DIRS[@]}"; do
 
   runStandup
 
-  # shellcheck disable=2164
-  cd "${BASE_DIR}"
+  cd ${BASE_DIR}
 done
 unset IFS
